---
- hosts: db
  become: yes

  vars_files:
    - ../vars.yml

  handlers:
    - name: restart firewalld
      service: name=firewalld state=restarted

  tasks:
    - name: Install MariaDB packages
      yum: name={{ item }} state=present
      with_items:
        - mariadb-server
        - MySQL-python
    - name: Ensure MariaDB is running
      service:
        name: mariadb
        state: started

    - name: Open port 3306
      firewalld:
        permanent: yes
        immediate: yes
        service: mysql
        state: enabled
      notify: restart firewalld
      tags:
        - firewall

    - name: Create DB for WordPress
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        state: present

    - name: Create DB user
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        host: "{{ app_host }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        state: present
