---
- name: "Provision Pfsense"
  hosts: all
  collections: pfsensible.core
  vars_files: 
    - vars.yml
  tasks:
    - name: "Install sudo package"
      package:
        name:
          - pfSense-pkg-sudo
        state: present

    - name: "Allow remote SSH"
      pfsense_rule:
        name: "Allow wan SSH"
        after: top
        action: pass
        interface: wan
        ipprotocol: inet
        protocol: tcp
        source: any
        destination: (self)
        destination_port: 22

    - name: "Configure lan interface"
      pfsense_interface:
        descr: LAN
        blockpriv: False
        interface: em1
        ipv4_address: "{{ lan_addr }}"
        ipv4_prefixlen: 24
        ipv4_type: static
        state: present
        enable: True

    - name: "Remove allow all rule"
      pfsense_rule:
        name: "Allow all ipv4+ipv6 via pfSsh.php"
        interface: wan
        state: absent
