---
- name: "Provision Pfsense"
  hosts: all
  collections: pfsensible.core
  vars_files: 
    - vars.yml
  tasks:
    - name: "Install sudo package"
      package:
        name:
          - pfSense-pkg-sudo
        state: present

    - name: "Add wan gateway"
      pfsense_gateway:
        name: wan_gateway
        interface: WAN
        gateway: "{{ wan_gateway }}"
        disabled: False
        ipprotocol: inet
        state: present

    - name: "Configure wan interface"
      pfsense_interface:
        descr: WAN
        blockpriv: False
        interface: em0
        ipv4_address: "{{ wan_addr }}"
        ipv4_gateway: wan_gateway
        ipv4_type: static
        state: present
        enable: True

    - name: "Allow remote SSH"
      pfsense_rule:
        name: "Allow wan SSH"
        after: top
        action: pass
        interface: wan
        ipprotocol: inet
        protocol: tcp
        source: any
        destination: (self)
        destination_port: 22
