---
- hosts: firewall
  gather_facts: yes

  roles:
    - name: firewall
      become: yes

- hosts: app
  roles:
    - name: httpd
      become: yes

- hosts: db
  roles:
    - name: mariadb
      become: yes
